name: "Update Homebrew Formula"
description: "A reusable homebrew formula action that checks out a taps code and updates the given formula"

inputs:
  formula-name:
    description: "The name of the formula to update"
    required: true
  formula-tag:
    description: "The tag of the formula file"
    required: true
  formula-hash:
    description: "The SHA256 hash of the formula file"
    required: true
  owner:
    description: "The owner of the formula"
    required: true
  repo:
    description: "The repository of the formula"
    required: false
    default: "formula-name"
  branch:
    description: "The branch of the formula"
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Get Repo Info
      id: repo
      uses: ./.github/actions/repo-info

    - name: Diff Repo Info for new releases/tags
      id: diff
      shell: bash
      run: |
        # Diff ${{ steps.repo.outputs.info }}

    - name: Get Missing Formulas
      if: ${{ steps.diff.outputs.latest != inputs.updated_at }}
      id: missing
      shell: bash
      run: |
        # Diff ${{ steps.repo.outputs.info }}
        echo "missing=$(cat /tmp/updates.json | jq -c '.')" >> $GITHUB_OUTPUT
        echo "update_count=$(cat /tmp/updates.json | jq '. | length')" >> $GITHUB_OUTPUT
